### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by pidanou** [pidanou/helmtui#9]
Following the introduction of tests #7 (thanks to @kek-Sec), we should add CI to run those tests.
Also, adding some rulesets for branches and PR would be a great addition.

**Comment by george-petrakis** [comment]
Take a look at the CI for a go project of mine , you might be able to adjust it to fit your needs , lmk if you need any help. https://github.com/kek-Sec/GopherDrop/blob/main/.github/workflows/build%26test.yaml
